name: ml_dev_webApp
dependencies:
  - python=3.8
  - numpy
  - keras
  # if you have nvidia GPU change next line to tensorflow-gpu
  - tensorflow
  - pandas
  - scikit-learn
  - pip
  - pip:
      - opencv-contrib-python
      - streamlit
      - sklearn
      - yfinance

